# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Build settings
remote_theme: jekyll/minima

# lots of changes upcoming ... see the github readme 
minima:
  skin: auto 
  social_links:
    - { platform: github,  user_url: "https://github.com/godfrey-cw" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/godfrey-cw/" }

title: Charles Godfrey
header_pages:
- index.md
- resume.md

description: >
  Home Page
  
author:  
  name: Charles Godfrey
  email: "godfrey.cw@gmail.com"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - quick_update.zsh

